# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-20 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessories',
            name='isAccessory',
            field=models.BooleanField(default=False),
        ),
    ]
