# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hearing_aid',
            new_name='Aid',
        ),
    ]
