# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190912_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aid',
            old_name='name',
            new_name='brand',
        ),
    ]
