# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-19 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20190919_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_type',
        ),
    ]
