# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-23 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_model_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Product_Addon',
        ),
    ]
